name: publish www
on:
  schedule:
    # run once a week on Sunday at 12AM
    - cron: '0 0 * * 0'
jobs:
  build-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: false
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - run: pnpm install --frozen-lockfile --silent
      - run: pnpm build-www
      - run: pnpm run --dir apps/www publish
